apiVersion: v1
kind: Service
metadata:
  name: {{ include "krakend.fullname" . }}
  labels:
    {{- include "krakend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
    - port: {{ .Values.monitoring.port }}
      targetPort: {{ .Values.monitoring.targetPort }}
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.internalPort }}
      targetPort: http-internal
      protocol: TCP
      name: http-internal
  selector:
    {{- include "krakend.selectorLabels" . | nindent 4 }}
