apiVersion: v2
name: frinx-machine
description: Kubernetes deployment of FRINX-machine
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 6.0.0
maintainers:
  - name: FRINX
dependencies:

  # Frinx Machine Core

  - name: krakend
    repository: https://FRINXio.github.io/helm-charts
    version: 3.1.0
    condition: krakend.enabled

  - name: frinx-frontend
    repository: https://FRINXio.github.io/helm-charts
    version: 4.0.0
    condition: frinx-frontend.enabled

  - name: resource-manager
    repository: https://FRINXio.github.io/helm-charts
    version: 2.0.0
    condition: resource-manager.enabled

  - name: workflow-manager
    repository: https://FRINXio.github.io/helm-charts
    version: 3.0.0
    condition: workflow-manager.enabled

  - name: inventory
    repository: https://FRINXio.github.io/helm-charts
    version: 5.0.0
    condition: inventory.enabled

  - name: uniconfig
    repository: https://FRINXio.github.io/helm-charts
    version: 6.0.0
    condition: uniconfig.enabled

  - name: topology-discovery
    version: 3.0.0
    repository: https://FRINXio.github.io/helm-charts
    condition: topology-discovery.enabled

  - name: oauth2-proxy
    repository: https://oauth2-proxy.github.io/manifests
    version: 6.24.1
    condition: oauth2-proxy.enabled
