apiVersion: v2
name: frinx-machine-monitoring
description: Kubernetes deployment of FRINX-machine
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 0.0.1
appVersion: 7.0.0
maintainers:
  - name: FRINX
dependencies:

  - name: grafana
    repository: "https://grafana.github.io/helm-charts"
    version: 7.3.1
    condition: grafana.enabled

  - name: frinx-grafana-configs
    repository: "https://FRINXio.github.io/helm-charts"
    version: 1.x.x
    condition: grafana.enabled

  - name: influxdb2
    repository: "https://helm.influxdata.com"
    version: 2.1.2
    condition: influxdb2.enabled

  - name: telegraf-ds
    repository: https://helm.influxdata.com
    version: 1.1.24
    condition: telegraf-ds.enabled

  - name: loki
    repository: https://grafana.github.io/helm-charts
    version: 2.16.0
    condition: loki.enabled

  - name: promtail
    repository: https://grafana.github.io/helm-charts
    version: 6.15.5
    condition: loki.enabled
