apiVersion: v2
name: frinx-machine-crds
description: Kubernetes deployment of FRINX-machine
icon: https://avatars.githubusercontent.com/u/23452093?s=200&v=4
type: application
version: 0.0.1
appVersion: 7.0.0
maintainers:
  - name: FRINX
dependencies:

  - name: kube-arangodb
    version: 1.2.38
    repository: https://arangodb.github.io/kube-arangodb
    condition: kube-arangodb.enabled

  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts
    version: 0.20.2
    condition: cloudnative-pg.enabled
